name: Heresy Validations
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out game system to horus-heresy
        uses: actions/checkout@v4
      - name: Checking out BSCopy
        uses: actions/checkout@v4
        with:
          repository: 'nstephenh/bscopy'
          path: 'tests/BSCopy'
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Run tests
        run: python3 validatehh3.py
        working-directory: tests/
        env:
          DEFAULT_DATA_DIRECTORY: ${{ github.workspace }}/..